In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("03_netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
print(df.isnull().sum())

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [4]:


df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Not available')
df.dropna(subset=['country'], inplace=True)  # dropna on df directly is okay

In [5]:
# Content type count
# Find how many entries are Movies and how many are TV Shows.
df["type"].value_counts()

type
Movie      5691
TV Show    2285
Name: count, dtype: int64

In [6]:
# Top countries with the most Netflix content
# Find top 10 countries by the number of titles produced.

df["country"].value_counts().head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [7]:
# Top countries with the most Netflix content
# Find top 10 countries by the number of titles produced.

top_countries = df['country'].value_counts().head(10)
print(top_countries)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [8]:
# Top directors
# Identify the 10 directors with the most Netflix titles.
top_director=df["director"].value_counts().head(10)
top_director

director
Unknown                   2225
Raúl Campos, Jan Suter      18
Marcus Raboy                15
Jay Karas                   14
Cathy Garcia-Molina         13
Jay Chapman                 12
Martin Scorsese             12
Youssef Chahine             12
Steven Spielberg            11
Don Michael Paul            10
Name: count, dtype: int64

In [9]:
# Most frequent genres
# Find which categories (from listed_in) are most common.
most_genre=df["listed_in"].value_counts().head(10)
most_genre

listed_in
Documentaries                                       343
Dramas, International Movies                        337
Stand-Up Comedy                                     303
Comedies, Dramas, International Movies              260
Dramas, Independent Movies, International Movies    243
Children & Family Movies, Comedies                  181
Kids' TV                                            176
Documentaries, International Movies                 165
Dramas, International Movies, Romantic Movies       163
Comedies, International Movies                      155
Name: count, dtype: int64

In [10]:
# 1. Split the categories by comma, create a list of all categories
all_categories = df['listed_in'].str.split(', ').explode()

# 2. Count the occurrences of each category
category_counts = all_categories.value_counts()

# 3. Show top 10 most common categories
print(category_counts)

listed_in
International Movies            2543
Dramas                          2317
Comedies                        1580
International TV Shows          1128
Action & Adventure               817
Documentaries                    794
Independent Movies               745
TV Dramas                        663
Romantic Movies                  588
Thrillers                        549
Children & Family Movies         535
TV Comedies                      501
Crime TV Shows                   421
Kids' TV                         370
Horror Movies                    340
Docuseries                       330
Music & Musicals                 328
Stand-Up Comedy                  311
Romantic TV Shows                299
Sci-Fi & Fantasy                 242
British TV Shows                 237
Reality TV                       205
Sports Movies                    201
Anime Series                     154
TV Action & Adventure            153
Spanish-Language TV Shows        145
Korean TV Shows                  136
Classic Movies                   115
LGBTQ Movies                      97
TV Mysteries                      92
Science & Nature TV               82
TV Sci-Fi & Fantasy               79
TV Horror                         72
Cult Movies                       70
Teen TV Shows                     66
Anime Features                    63
Faith & Spirituality              63
TV Thrillers                      53
Stand-Up Comedy & Talk Shows      47
Movies                            34
Classic & Cult TV                 27
TV Shows                           9
Name: count, dtype: int64

In [11]:
# Content released per year
#Find the number of titles released each year (from release_year).
year_wise = df["release_year"].value_counts().sort_index()
year_wise

release_year
1942       2
1943       3
1944       3
1945       4
1946       2
        ...
2017     966
2018    1038
2019     913
2020     852
2021     383
Name: count, Length: 73, dtype: int64

In [12]:
# Longest and shortest titles
# Identify the titles with the longest and shortest names.
df["title_length"]=df["title"].apply(len)
longest = df.loc[df["title_length"].idxmax()]["title"]
shortest = df.loc[df["title_length"].idxmin()]["title"]

In [13]:
longest

'Jim & Andy: The Great Beyond - Featuring a Very Special, Contractually Obligated Mention of Tony Clifton'

In [14]:
shortest

'H'

In [15]:
# Filtering & Grouping Filter for Indian content
# Find all titles produced in India.
indian_titles =df[df["country"].str.contains("India",na=False)]
print(indian_titles[['title', 'type', 'release_year', 'director']])

                    title     type  release_year                 director
4            Kota Factory  TV Show          2021                  Unknown
24                  Jeans    Movie          1998               S. Shankar
29               Paranoia    Movie          2013           Robert Luketic
39           Chhota Bheem  TV Show          2021                  Unknown
50          Dharmakshetra  TV Show          2014                  Unknown
...                   ...      ...           ...                      ...
8773  Yanda Kartavya Aahe    Movie          2006             Kedar Shinde
8775      Yeh Meri Family  TV Show          2018                  Unknown
8798             Zed Plus    Movie          2014  Chandra Prakash Dwivedi
8799                Zenda    Movie          2009           Avadhoot Gupte
8806               Zubaan    Movie          2015              Mozez Singh

[1046 rows x 4 columns]

In [16]:
#Filter by year
#Find all shows added in a specific year (e.g., 2020).
df[df["release_year"]==2020]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,title_length
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not available,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",20
17,s18,TV Show,Falsa identidad,Unknown,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...,15
32,s33,TV Show,Sex Education,Unknown,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...,13
84,s85,Movie,Omo Ghetto: the Saga,"JJC Skillz, Funke Akindele","Funke Akindele, Ayo Makun, Chioma Chukwuka Akp...",Nigeria,"September 10, 2021",2020,TV-MA,147 min,"Action & Adventure, Comedies, Dramas",Twins are reunited as a good-hearted female ga...,20
126,s127,Movie,Shikara,Vidhu Vinod Chopra,"Aadil Khan, Sadia Khateeb, Zain Khan Durrani, ...",India,"September 2, 2021",2020,TV-14,115 min,"Dramas, International Movies, Romantic Movies",A couple must strive to remain resilient after...,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5972,s5973,Movie,#cats_the_mewvie,Michael Margolis,Not available,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...,16
7594,s7595,Movie,Norm of the North: Family Vacation,Anthony Bell,"Andrew Toth, Lisa Durupt, Jonathan Holmes, Pau...",United States,"May 25, 2020",2020,TV-Y7,89 min,Children & Family Movies,"Stressed by his duties as king and father, Nor...",34
8099,s8100,Movie,Straight Up,James Sweeney,"James Sweeney, Katie Findlay, Randall Park, Hi...",United States,"June 26, 2020",2020,TV-MA,96 min,"Comedies, Independent Movies, LGBTQ Movies",When a gay brainiac with OCD questions his ide...,11
8125,s8126,TV Show,Super Wings,Unknown,"Luca Padovan, Evan Smolin, Junah Jang, Colin C...","United States, South Korea, China","December 1, 2020",2020,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows",A cheerful jet and his transforming pals striv...,11
8132,s8133,TV Show,Surviving R. Kelly Part II: The Reckoning,Unknown,R. Kelly,United States,"April 13, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries",As more women come forward with harrowing accu...,41

In [17]:
#Find all horror movies
#Filter titles that belong to the “Horror” genre.

horror_movie =df[(df["type"]=="Movie")& (df["listed_in"].str.contains("Horror",na=False))]
print(horror_movie[["title","country","release_year","listed_in"]])

                  title                country  release_year  \
28           Dark Skies          United States          2013
42               Jaws 2          United States          1978
43               Jaws 3          United States          1983
44    Jaws: The Revenge          United States          1987
200     Krishna Cottage                  India          2004
...                 ...                    ...           ...
8722  What Lies Beneath          United States          2000
8760   Would You Rather          United States          2013
8765                 XX  Canada, United States          2017
8782        Yoga Hosers          United States          2016
8804         Zombieland          United States          2009

                                              listed_in
28                      Horror Movies, Sci-Fi & Fantasy
42                     Dramas, Horror Movies, Thrillers
43         Action & Adventure, Horror Movies, Thrillers
44         Action & Adventure, Horror Movies, Thrillers
200   Action & Adventure, Horror Movies, Internation...
...                                                 ...
8722                           Horror Movies, Thrillers
8760       Horror Movies, Independent Movies, Thrillers
8765                                      Horror Movies
8782        Comedies, Horror Movies, Independent Movies
8804                            Comedies, Horror Movies

[340 rows x 4 columns]

In [18]:
# Find all shows/movies by a specific director
# Example: All titles directed by “Christopher Nolan”.
sepecific_director =df[df["director"].str.contains("Christopher Nolan",na=False)]
print(sepecific_director[["title","type","country","release_year"]])
 # OR
specific_director =df[df["director"].str.contains("Christopher Nolan", na=False)]
print(specific_director[["title", "type", "country","release_year"]])

         title   type                        country  release_year
340  Inception  Movie  United States, United Kingdom          2010
         title   type                        country  release_year
340  Inception  Movie  United States, United Kingdom          2010

In [19]:
# Group by country
# Group data by country and count the number of titles.
country_title_counts = df.groupby('country').size().sort_values(ascending=False)
print(country_title_counts)

country
United States          2818
India                   972
United Kingdom          419
Japan                   245
South Korea             199
                       ...
Australia, Iraq           1
Venezuela                 1
Venezuela, Colombia       1
West Germany              1
, South Korea             1
Length: 748, dtype: int64